### ISSUE TITLE
海光单机多DCU卡训练异常 assert loss <= 1 assertionerror

### ISSUE THREAD

**Issue by chenzhijun45** [PaddlePaddle/PaddleOCR#10056]
进行单机多卡训练时，经常出现 assert loss <= 1 assertionerror 异常，请问可能是什么原因导致的呢？并非一定出现该问题，但是经常出现。

![aa](https://github.com/PaddlePaddle/PaddleOCR/assets/39179856/46c6e94e-f263-456d-a54e-93fc53bce778)

**Comment by andyjpaddle** [comment]
运行命令是啥？

**Comment by chenzhijun45** [comment]
> 

python3 -m paddle.distributed.launch --gpus '0,1' tools/train.py -c configs/det/det_mv3_db.yml \
     -o Global.pretrained_model=./pretrain_models/MobileNetV3_large_x0_5_pretrained

是在conda虚拟环境运行的

**Comment by masoudMZB** [comment]
same error here.
any progress since then?

**Comment by chenzhijun45** [comment]
> [SOLVED]
> 
> the problem is with data. try to find which of your images have a problem

Okay, thank you for your reply.

**Comment by zhangqiqi1228** [comment]
> [SOLVED]
> 
> the problem is with data. try to find which of your images have a problem.

Hi, could you explain more about it? 

I generated dataset according to OCR Dataset:
ch4_test_images/img_61.jpg    [{"transcription": "MASA", "points": [[310, 104], [416, 141], [418, 216], [312, 179]]}, {...}]

And I used the following command for training: 
python tools/train.py -c configs/det/det_r50_vd_db.yml -o Global.pretrained_model=./pretrain_models/det_r50_vd_db_v2.0_train/best_accuracy

But I still get the "assert loss <= 1" error? 
Is it because I added Chinese and special symbols to train the DB detection model?

**Comment by zhangqiqi1228** [comment]
> 进行单机多卡训练时，经常出现 assert loss <= 1 assertionerror 异常，请问可能是什么原因导致的呢？并非一定出现该问题，但是经常出现。
> 
> ![aa](https://user-images.githubusercontent.com/39179856/241822839-46c6e94e-f263-456d-a54e-93fc53bce778.png)

请问你后来解决了么？具体是数据集什么方面的问题呀？
