### ISSUE TITLE
PPPCRlabel启动不了

### ISSUE THREAD

**Issue by forAlgorithm** [PaddlePaddle/PaddleOCR#10328]
n.exe e:/anaconda/conda/envs/pytorch_gpu/Lib/site-packages/PPOCRLabel/PPOCRLabel.py
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.

**Comment by forAlgorithm** [comment]
<img width="848" alt="9f4baf7b7d6454b7b0f37782e578b2f" src="https://github.com/PaddlePaddle/PaddleOCR/assets/47384518/a1954ca2-0844-4ce0-8561-b08770375787">

**Comment by livingbody** [comment]
###### 这个有可能是因为系统环境中存在多个版本的OpenMP库导致，可以把环境变量KMP\_DUPLICATE\_LIB\_OK设置成True试试。

vbnet

复制代码

`OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program.
That is dangerous, since it can degrade performance or cause incorrect results. 
The best thing to do is to ensure that only a single OpenMP runtime is linked into the process,
 e.g. by avoiding static linking of the OpenMP runtime in any library.
 As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute,
 but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.` 

###### 在代码中解决方案如下：

lua

复制代码

`import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'` 

### 或：

1. 查看文件链接的OpenMP library, 只使用一个。
2. 推荐使用动态库:libiomp5md.dll
3. 如果第三方库使用libguide40.dll, 使用libiomp5md.dll 重新编译库文件。

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
