### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yuanjie-ai** [PaddlePaddle/PaddleOCR#10477]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/20265321/cded71f8-dc30-4c09-b48c-d25f1f2c7e93)

**Comment by shiyutang** [comment]
It seems that there is an issue with the code you are using. The error message "no module named tools.infer" indicates that the module "tools.infer" is not found in the Python environment.

To resolve this issue, you can try the following steps:

1. Make sure that the "tools" module is installed in your Python environment. You can install it by running `pip install "paddleocr>=2.0.1" # Recommend to use version 2.0.1+`.

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/quickstart_en.md#12-install-paddleocr-whl-package

2. Confirm that the "tools" module contains the "infer" submodule. You can check the package structure by running `python -c "import tools; print(dir(tools))"`. If the "infer" submodule is not listed, there might be an issue with the installation.

3. If you have cloned the project from a repository, make sure that the "tools" module is included in the project directory and that the path to the module is correctly set.

4.  If you have made any modifications to the code, double-check that you haven't accidentally removed or renamed the "infer" submodule.
 
If the issue persists, please provide more information about the project and the steps you have taken so far, so that I can assist you further.

**Comment by UserWangZz** [comment]
该issue长时间未更新，暂将此issue关闭，如有需要可重新开启。
