### ISSUE TITLE
PaddleServing预测报错

### ISSUE THREAD

**Issue by xiulianzw** [PaddlePaddle/PaddleOCR#1175]
安装官方提供的文档安装了PaddleServing相关的包，版本信息如下：
python版本3.7
`
paddle-serving-app        0.0.0
paddle-serving-client     0.0.0
paddle-serving-server     0.0.0
paddle-serving-server-gpu 0.0.0.trt
paddlehub                 1.8.3
paddlepaddle-gpu          2.0.0b0
`
CUDA的版本是10.1，在使用GPU的情况下能够正常启动，在使用`python pdserving_client.py image_path`预测时报如下错误

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   void paddle::ZeroCopyTensor::copy_from_cpu<float>(float const*)
1   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
2   paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
3   paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
4   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
5   paddle::memory::allocation::RetryAllocator::AllocateImpl(unsigned long)
6   paddle::memory::allocation::AutoGrowthBestFitAllocator::AllocateImpl(unsigned long)
7   paddle::memory::allocation::AlignedAllocator::AllocateImpl(unsigned long)
8   paddle::memory::allocation::CUDAAllocator::AllocateImpl(unsigned long)
9   paddle::platform::RecordedCudaMalloc(void**, unsigned long, int)
10  paddle::platform::GetCurrentDeviceId()
11  paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
12  std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
13  paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(3), initialization error.
  [Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:190)

**Comment by wangjiawei04** [comment]
用的是paddle_serving_server_gpu这个包对吧
CUDA的so有没有在LD_LIBRARY_PATH目录下

**Comment by steelOneself** [comment]
谢谢大神回复@wangjiawei04 
嗯对的我是用的GPU版本的，CUDA的so在LD_LIBRARY_PATH目录下，我用单个文字检测模型det_local_server.py测试过没问题，后面用的串联的ocr_local_server.py，在预测的时候报错了，定位了一下报错的行

This API will be deprecated later. Please do not use it
W1117 13:13:08.053695 24192 analysis_predictor.cc:578] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I1117 13:13:08.053781 24192 analysis_predictor.cc:139] Profiler is deactivated, and no profiling report will be generated.
I1117 13:13:08.074901 24192 analysis_predictor.cc:952] MODEL VERSION: 2.0.0
I1117 13:13:08.074934 24192 analysis_predictor.cc:954] PREDICTOR VERSION: 2.0.0
I1117 13:13:08.075345 24192 analysis_predictor.cc:491] ir_optim is turned off, no IR pass will be executed
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I1117 13:13:08.099320 24192 ir_params_sync_among_devices_pass.cc:41] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [ir_graph_to_program_pass]
I1117 13:13:08.146216 24192 analysis_predictor.cc:513] ======= optimize end =======
I1117 13:13:08.146528 24192 naive_executor.cc:102] ---  skip [feed], feed -> image
I1117 13:13:08.148533 24192 naive_executor.cc:102] ---  skip [save_infer_model/scale_0.tmp_0], fetch -> fetch
I1117 13:13:08.148547 24192 naive_executor.cc:102] ---  skip [save_infer_model/scale_1.tmp_0], fetch -> fetch
I1117 13:13:08.149823 24192 analysis_predictor.cc:139] Profiler is deactivated, and no profiling report will be generated.
I1117 13:13:08.155850 24192 analysis_predictor.cc:952] MODEL VERSION: 2.0.0
I1117 13:13:08.155876 24192 analysis_predictor.cc:954] PREDICTOR VERSION: 2.0.0
I1117 13:13:08.156101 24192 analysis_predictor.cc:491] ir_optim is turned off, no IR pass will be executed
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I1117 13:13:08.199632 24192 ir_params_sync_among_devices_pass.cc:41] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [ir_graph_to_program_pass]
I1117 13:13:08.287137 24192 analysis_predictor.cc:513] ======= optimize end =======
I1117 13:13:08.287477 24192 naive_executor.cc:102] ---  skip [feed], feed -> image
I1117 13:13:08.289135 24192 naive_executor.cc:102] ---  skip [save_infer_model/scale_0.tmp_0], fetch -> fetch
This API will be deprecated later. Please do not use it
mkdir: cannot create directory ‘workdir’: File exists
This API will be deprecated later. Please do not use it
I1117 13:13:41.688313 24289 analysis_predictor.cc:513] ======= optimize end =======
I1117 13:13:41.688539 24289 naive_executor.cc:102] ---  skip [feed], feed -> image
I1117 13:13:41.690017 24289 naive_executor.cc:102] ---  skip [save_infer_model/scale_0.tmp_0], fetch -> fetch
I1117 13:13:41.690027 24289 naive_executor.cc:102] ---  skip [save_infer_model/scale_1.tmp_0], fetch -> fetch
[2020-11-17 13:13:41,806] ERROR in app: Exception on /ocr/prediction [POST]
Traceback (most recent call last):
  File "/home/**/anaconda3/envs/ocr/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/**/anaconda3/envs/ocr/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/**/anaconda3/envs/ocr/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/**/anaconda3/envs/ocr/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/**/anaconda3/envs/ocr/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/**/anaconda3/envs/ocr/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/**/anaconda3/envs/ocr/lib/python3.7/site-packages/paddle_serving_server_gpu/web_service.py", line 230, in run
    return self.get_prediction(request)
  File "/home/**/anaconda3/envs/ocr/lib/python3.7/site-packages/paddle_serving_server_gpu/web_service.py", line 171, in get_prediction
    request.json["fetch"])
  File "/home/**/workspace/text_ocr/PaddleOCR/deploy/pdserving/ocr_local_server.py", line 96, in preprocess
    feed, fetch, self.tmp_args = self.text_system.preprocess(im)
  File "/home/**/workspace/text_ocr/PaddleOCR/deploy/pdserving/ocr_local_server.py", line 57, in preprocess
    fetch_map = self.det_client.predict(feed, fetch)
  File "/home/**/anaconda3/envs/ocr/lib/python3.7/site-packages/paddle_serving_app/local_predict.py", line 127, in predict
    input_tensor.copy_from_cpu(feed[name])
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   void paddle::ZeroCopyTensor::copy_from_cpu<float>(float const*)
1   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
2   paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
3   paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
4   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
5   paddle::memory::allocation::RetryAllocator::AllocateImpl(unsigned long)
6   paddle::memory::allocation::AutoGrowthBestFitAllocator::AllocateImpl(unsigned long)
7   paddle::memory::allocation::AlignedAllocator::AllocateImpl(unsigned long)
8   paddle::memory::allocation::CUDAAllocator::AllocateImpl(unsigned long)
9   paddle::platform::RecordedCudaMalloc(void**, unsigned long, int)
10  paddle::platform::GetCurrentDeviceId()
11  paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
12  std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
13  paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(3), initialization error.
  [Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:190)

Debug的时候，跑到**local_predict.py**的**input_tensor.copy_from_cpu(feed[name])**就出问题了，不能继续往下跑了。

**Comment by wangjiawei04** [comment]
看起来是缺so文件。
你的环境是CUDA 9 还是10 CUDNN是7对吧

**Comment by steelOneself** [comment]
CUDA10.1和cudnn8.02，这个版本的目前支持吗？

**Comment by wangjiawei04** [comment]
看起来不支持， paddlepaddle-gpu==1.8.5.post107 目前 应该是这个版本。 107的10就是CUDA10，7就是CUDNN7.
看看降级到CUDNN 7.6 看看

**Comment by wangjiawei04** [comment]
实在不行可以用官方推荐的docker哈

**Comment by steelOneself** [comment]
我刚刚试了一下还是你说的这些环境还是不行。我还是直接用docker吧，谢谢大神。
