### ISSUE TITLE
Cyrillic text recognition

### ISSUE THREAD

**Issue by KaraElan** [PaddlePaddle/PaddleOCR#13468]
As far as I understand, currently it is a bug of Cyrillic-based languages recognition.

### Discussed in https://github.com/PaddlePaddle/PaddleOCR/discussions/13309

<div type='discussions-op-text'>

<sup>Originally posted by **KaraElan** July  8, 2024</sup>
Hello

I am trying to recognize text written with Cyrillic alphabet (Russian, to be exact). Yet when I enable "rec""cyrillic" I still get Latin characters in the answer and, as far as I see, "dict_path": "./ppocr/utils/dict/cyrillic_dict.txt" includes Latin. It drastically decreases the recognition accuracy as Latin and Cyrillic alphabets contain many similarly looking characters.

Is it possible to get an answer containing only Cyrillic characters automatically without retraining the model or doing some custom postprocessing? </div>

**Comment by UserWangZz** [comment]
Latin letters are included because they still appear in some scenes. Regarding the problem you mentioned, maybe you need to regenerate a dictionary containing only cyrillic characters to retrain the model. Or delete the Latin letters in the recognition results (but this is not an effective method, I think)

**Comment by omukesh** [comment]
which model you guys used as am in need of a cyrillic model which should also recognise the english / latin character and numbers
