### ISSUE TITLE
设置det=False，影响rec结果。

### ISSUE THREAD

**Issue by 2213500360** [PaddlePaddle/PaddleOCR#14358]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

result = ocr.ocr(img_path,  cls=False)
运行结果：
[[[80.0, 111.0], [442.0, 118.0], [441.0, 172.0], [79.0, 166.0]], ('今回の開発', 0.9162408709526062)] #识别内容正确
[[[489.0, 118.0], [717.0, 118.0], [717.0, 170.0], [489.0, 170.0]], ('を確認し', 0.9968138933181763)] #识别内容正确
[[[174.0, 180.0], [587.0, 180.0], [587.0, 234.0], [174.0, 234.0]], ('ご報告ください', 0.9931657910346985)]  #识别内容正确

result = ocr.ocr(img_path, **det=False**, cls=False)
运行结果：

('「"多点でとま取して', 0.4961227774620056)     #识别内容错误

其他参数没有任何修改，只是加了一个det=False就导致结果非常差。想要有好的结果就不能设置det=False吗？

### 🏃‍♂️ Environment (运行环境)

Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz   2.11 GHz  16.0 GB

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

from paddleocr import PaddleOCR
ocr = PaddleOCR(lang='japan',rec_model_dir="./japan_PP-OCRv4_rec_infer/")
img_path = './doc/img/123.png'
result = ocr.ocr(img_path,  cls=False)
for idx in range(len(result)):
    res = result[idx]
    for line in res:
        print(line)

**Comment by GreatV** [comment]
This issue arises because setting `det=False` disables the detection module in the OCR pipeline, which is responsible for identifying and cropping text regions from the image. Without this step, the recognizer directly processes the entire image as a single text region, leading to poor recognition results.

### Understanding the Issue

- **With `det=True`:** The OCR pipeline first detects text regions (using the detection model) and then sends these cropped regions to the recognition model. This step ensures that only relevant parts of the image are processed for recognition, leading to accurate results.
- **With `det=False`:** The detection step is skipped, and the entire image is sent to the recognizer as if it's a single text region. This often causes recognition errors since the recognizer is not designed to handle undetected raw images.

### Why This Happens

The text recognition model (`rec_model`) in PaddleOCR is trained to work on text crops, not entire images. Without the detection step, the recognizer doesn't have the benefit of focusing only on actual text regions.

### Key Points

- Ensure the input to the recognition model is a proper text crop.
- Using `det=False` assumes you handle text region cropping externally.

### Recommendation

**Avoid using `det=False` unless you have a clear reason to bypass text detection and are prepared to supply well-cropped text regions. For most use cases, keeping `det=True` will yield better and more consistent results.**

**Comment by GreatV** [comment]
除非有明确的理由跳过文本检测并且准备好提供裁剪良好的文本区域，否则请避免使用 `det=False`。对于大多数使用场景，保持 `det=True` 将会提供更好且更稳定的结果。

**Comment by 2213500360** [comment]
非常抱歉再次打扰，按照所说的需要加入文本检测才会有更好的结果。如果我想要微调res模型来获取更好的结果，是不是必须要让训练数据图片内文字必须在一行显示？

**Comment by GreatV** [comment]
是的 最好这么操作
