### ISSUE TITLE
not find model file path．/inference/db_det/ch_ppocr_mobile_v2.0_det_infer/model

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleOCR#1526]
ｉexecute python3 tools/infer/predict_det.py --image_dir=./doc/imgs_en/img_10.jpg" --det_model_dir="./inference/db_det/ch_ppocr_mobile_v2.0_det_infer"

it rasise not find model file path．/inference/db_det/ch_ppocr_mobile_v2.0_det_infer/model

the model file is in /inference/db_det/ch_ppocr_mobile_v2.0_det_infer why raise this error

thks

**Comment by WenmuZhou** [comment]
this model is here https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_det_infer.tar

**Comment by SanchiMittal** [comment]
Since the PR #1339 has been merged, I am getting the following error:

```
[2020/12/19 16:58:45] root INFO: not find model file path ./inference/ch_ppocr_server_v1.1_det_infer//inference.pdmodel
```

on running the following shell command from the root directory after following all the steps accurately as described in [quick start documentation](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/quickstart_en.md)

```
python3 tools/infer/predict_system.py --image_dir="./doc/imgs_en/img_10.jpg" --det_model_dir="./inference/ch_ppocr_server_v1.1_det_infer/"  --rec_model_dir="./inference/ch_ppocr_server_v1.1_rec_infer/" --cls_model_dir="./inference/ch_ppocr_mobile_v1.1_cls_infer/" --use_angle_cls=True --use_space_char=True
```

I have downloaded all the models appropriately as .tar files and unzipped them, in fact everything was working fine earlier.  Please let me know how can I solve this?

**Comment by WenmuZhou** [comment]
I noticed that you are using the 1.1 series model. The code corresponding to the 1.1 series model is under the develop branch. Try this code to see

**Comment by SanchiMittal** [comment]
Okay thanks! Where can I find the list of version 2.0 models?

**Comment by WenmuZhou** [comment]
[Here](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/models_list.md), the 2.0 code is under the dygraph branch, which is now the default branch

**Comment by SanchiMittal** [comment]
Yes that will work for me! Thanks a lot @WenmuZhou for the help!

**Comment by beidou-1** [comment]
一般都是和名字有关，把inference.pdmodel改成model试试，我在v20也遇到过这个问题。
