### ISSUE TITLE
Unable to recognize special characters ($)

### ISSUE THREAD

**Issue by suravijayjilla** [PaddlePaddle/PaddleOCR#2532]
![2](https://user-images.githubusercontent.com/48546629/115010143-b60fc000-9eca-11eb-89ce-54cefc685e9f.jpg)
[2.txt](https://github.com/PaddlePaddle/PaddleOCR/files/6324205/2.txt)

Hi,
We are getting a good results for alphanumeric texts for English language.
But unable to get a special characters, especially **( $ )** symbol.

Thanks,
Bharath J

**Comment by MissPenguin** [comment]
You can try the recently optimized English recognition model: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_en/models_list_en.md#english-recognition-model.

If you are using a self-trained model, it may be because there are too few training data with $ character, so you can add some such data to fine-tune your model.

**Comment by suravijayjilla** [comment]
Hi,

Thanks for your feedback.
But I don't know how to train for our custom data. Please guide me on this.
