### ISSUE TITLE
Intel MKL function load error: cpu specific dynamic library is not loaded.

### ISSUE THREAD

**Issue by jeffreykuang** [PaddlePaddle/PaddleOCR#2785]
the parameter is 

Namespace(cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='~/.paddleocr/2.1/cls', cls_thresh=0.9, det=True, det_algorithm='DB', det_db_box_thresh=0.5, det_db_thresh=0.3, det_db_unclip_ratio=1.6, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='~/.paddleocr/2.1/det/ch', drop_score=0.5, enable_mkldnn=False, gpu_mem=8000, image_dir='', ir_optim=True, label_list=['0', '180'], lang='ch', max_text_length=25, rec=True, rec_algorithm='CRNN', rec_batch_num=6, rec_char_dict_path='./ppocr/utils/ppocr_keys_v1.txt', rec_char_type='ch', rec_image_shape='3, 32, 320', rec_model_dir='~/.paddleocr/2.1/rec/ch_ppocr_server_v2.0_rec_infer', use_angle_cls=False, use_dilation=False, use_gpu=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_zero_copy_run=False)

The following is my envs:
>>> import numpy
>>> numpy.__version__
'1.19.1'
>>> import scipy
>>> scipy.__version__
'1.6.0'

I also try scipy 1.1.0

It also fails.

**Comment by LDOUBLEV** [comment]
You can try scipy 1.3.0 or install mkldnn in intel CPU. 

reference: https://github.com/PaddlePaddle/PaddleOCR/issues/440
![image](https://user-images.githubusercontent.com/26592129/118094011-c8651700-b400-11eb-895b-dfa1a1b09501.png)

![Uploading image.png…]()

**Comment by zhugw** [comment]
```
conda install nomkl
```
通过执行这一命令解决了

**Comment by jiafeng5513** [comment]
尝试以上方案均无效的朋友，可以尝试我的方法：
export OMP_NUM_THREADS=1

该方法来自：
https://community.intel.com/t5/Software-Archive/MKL-function-load-error-cpu-specific-dynamic-library-is-not/m-p/971767?profile.language=pt

原文：I learned that this problem will be fixed in MKL 11.1.1, which is available in November-December timeframe. A temporary workaround is to call sequential version of VML functions on MIC; that is, set OMP_NUM_THREADS=1 when calling a VML function.

我的调试过程：
1. scipy 从1.12.0 降级到1.6.0均无法解决此问题，继续降级会引发更多问题
2. conda install nomkl 无法解决
3. 通过grep -r 检索字符串“Intel MKL function load error: cpu specific dynamic library is not loaded.”能定位到两个so，通过ldd检查发现envs/audiollmsd/lib/python3.10/site-packages/intel_extension_for_pytorch/lib/libintel-ext-pt-cpu.so 存在 not fount的依赖，通过增补LD_LIBRARY_PATH 的方式无法解决，通过对比其他conda环境中的同样的so，发现同样存在这个现象，故排除嫌疑
4. 检索到上述intel社区中的问答，实验有效

我的环境
ubuntu 22.04
oneAPI 2024.0
python 3.10
paddlespeech==1.3.0
