### ISSUE TITLE
多卡训练加载数据进GPU异常

### ISSUE THREAD

**Issue by Gaoxj2020** [PaddlePaddle/PaddleOCR#3050]
使用多卡训练时，运行
`python3 -m paddle.distributed.launch --log_dir=./debug/ --gpus '0,1,2,3'  tools/train.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml`
卡在这个界面
![image](https://user-images.githubusercontent.com/45119560/121154251-68378880-c879-11eb-94a9-18142f06eab7.png)
观察GPU状态，GPU始终在加载443M数据进显存后停止加载
![image](https://user-images.githubusercontent.com/45119560/121154368-8309fd00-c879-11eb-8642-f411e820664f.png)
一直卡在上述状态，直到出现这个错误
![image](https://user-images.githubusercontent.com/45119560/121154621-afbe1480-c879-11eb-880c-9dbc4caea6fa.png)
训练异常终止。
请问该如何解决此问题呢？

**Comment by MissPenguin** [comment]
num worker改成0试试呢

**Comment by MissPenguin** [comment]
单卡训练能跑吗，python3 tools/train.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml

**Comment by Gaoxj2020** [comment]
可以

发自我的iPhone

在 2021年6月9日，上午10:52，MissPenguin ***@***.***> 写道：

﻿

单卡训练能跑吗，python3 tools/train.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml

**Comment by MissPenguin** [comment]
是不是没装nccl，参考这个issue的解决方案试试：https://github.com/PaddlePaddle/PaddleOCR/issues/1351

**Comment by 01Juw** [comment]
> 使用多卡训练时，运行
> `python3 -m paddle.distributed.launch --log_dir=./debug/ --gpus '0,1,2,3' tools/train.py -c configs/rec/ch_ppocr_v2.0/rec_chinese_lite_train_v2.0.yml`
> 卡在这个界面
> ![image](https://user-images.githubusercontent.com/45119560/121154251-68378880-c879-11eb-94a9-18142f06eab7.png)
> 观察GPU状态，GPU始终在加载443M数据进显存后停止加载
> ![image](https://user-images.githubusercontent.com/45119560/121154368-8309fd00-c879-11eb-8642-f411e820664f.png)
> 一直卡在上述状态，直到出现这个错误
> ![image](https://user-images.githubusercontent.com/45119560/121154621-afbe1480-c879-11eb-880c-9dbc4caea6fa.png)
> 训练异常终止。
> 请问该如何解决此问题呢？

这个问题有解决吗 我这边也遇到同样情况 单卡正常 多卡卡不动

**Comment by Evezerest** [comment]
更新paddle版本可以解决吗？

**Comment by Gaoxj2020** [comment]
> 更新paddle版本可以解决吗？

具体什么原因我忘记了，我好像是通过省级cuda 解决了，显卡a100

**Comment by 01Juw** [comment]
paddle版本都试过不行 cuda版本也尝试了 4卡的rtx5000怎么都不行&nbsp; 后来换成4卡的 3090可以了&nbsp; &nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月11日(星期三) 上午9:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 多卡训练加载数据进GPU异常 (#3050)





  
更新paddle版本可以解决吗？
  
具体什么原因我忘记了，我好像是通过省级cuda 解决了，显卡a100
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 01Juw** [comment]
paddle版本都试过不行 cuda版本也尝试了 4卡的rtx5000怎么都不行&nbsp; 后来换成4卡的 3090可以了&nbsp; &nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月10日(星期二) 下午5:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 多卡训练加载数据进GPU异常 (#3050)





 
更新paddle版本可以解决吗？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
