### ISSUE TITLE
How to separate word around spaces in text detection? 

### ISSUE THREAD

**Issue by manjrekarom** [PaddlePaddle/PaddleOCR#3138]
First of all, thank for this wonderful product. There aren't many OCR engines as fast and as accurate as PaddleOCR. 

Coming to my problem, I would like to get bounding boxes around text like this (obtained with mmocr):
<img src="https://user-images.githubusercontent.com/25369448/122651896-58f9ea00-d159-11eb-90ba-214c1dfd24f3.jpg" width="70%"/>

Instead of this (PaddleOCR):
<img src="https://user-images.githubusercontent.com/25369448/122651899-5b5c4400-d159-11eb-8922-5e2e906b893d.jpg" width="70%"/>

Is there some setting that I can tweak or a place in the code where I can make this change? Or is this really how the model itself is trained to make predictions?

Thank you!

**Comment by LDOUBLEV** [comment]
Hi，the ch_ppocr_mobile_det model outputs text line-level boxes instead of word-level text boxes as the text line-level training annotation.
U can try the en_ppocr_det model which trained using word-level annotation. 
https://github.com/PaddlePaddle/PaddleOCR/blob/release%2F2.1/doc/doc_en/algorithm_overview_en.md#algorithm-introduction
![image](https://user-images.githubusercontent.com/26592129/122674731-037d1600-d209-11eb-8a95-7255da0442da.png)

**Comment by manjrekarom** [comment]
It is working. Thanks a lot.

**Comment by Akhilesh64** [comment]
Hi @manjrekarom which model did you use finally and did it solve your problem ??

**Comment by manjrekarom** [comment]
Yes it did. I used the ones highlighted in the image above.
