### ISSUE TITLE
训练PGNet时，多边形框label需要保证点数相同吗

### ISSUE THREAD

**Issue by XiangTodayEatsWhat** [PaddlePaddle/PaddleOCR#3452]
使用PGNet对我自己的数据集进行训练时，出现了以下错误：
error happened with msg: setting an array element with a sequence.

对比了我的数据集和total_text数据集，total_text.txt标签信息存储的points似乎具有相同的数目（14个点），而我这边的数据集中，不同的文本框边数不同。

我手动扩充了一些文本框的点（在原来的边上取一些点加到points里），然后发现报了下面这个错：
Cross point does not exist.

想请问下PGNet训练时能否处理这种label里面点数不同的问题呢？如果可以的话应该怎么操作呢？如果不可以的话应该是不是只能修改成点数相同的标注方法呢，上面的报错又应该怎么解决呢？

求指导，谢谢大家~

**Comment by littletomatodonkey** [comment]
训练数据需要保证是14点哈

**Comment by v413945333** [comment]
> 训练数据需要保证是14点哈
好的，谢谢您！请问这部分代码具体在哪里呢？我想修改源码实现不同点数的训练，不知道可不可行，也没找到应该改代码的哪块
o(╥﹏╥)o

**Comment by wu-yakun** [comment]
的确，我发现官方给的例子里也是用14个点表示一个文本框。

**Comment by wu-yakun** [comment]
将配置文件中PGProcessTrain的batch_size修改为4就行，原始的batch_size为14。亲测有效。

**Comment by v413945333** [comment]
> 将配置文件中PGProcessTrain的batch_size修改为4就行，原始的batch_size为14。亲测有效。

唔我理解您可能是全部文本框都是四边形？但是我这边的数据其实不一样的文本框边数不一样，就是可能有矩形框，也可能有五边形、六边形这样子，仅调整batchsize还是会报同样的错误。
以及有点不解的是，这样改batchsize有效的话，那它的batchsize不是通常理解的一个batch的样本个数吗？

**Comment by lzzzzj** [comment]
> 将配置文件中PGProcessTrain的batch_size修改为4就行，原始的batch_size为14。亲测有效。

请问底下的loader的batch_size_per_card也要改成4吗

**Comment by guochengzhen** [comment]
> 使用PGNet对我自己的数据集进行训练时，出现了以下错误：
> error happened with msg: setting an array element with a sequence.
> 
> 对比了我的数据集和total_text数据集，total_text.txt标签信息存储的points似乎具有相同的数目（14个点），而我这边的数据集中，不同的文本框边数不同。
> 
> 我手动扩充了一些文本框的点（在原来的边上取一些点加到points里），然后发现报了下面这个错：
> Cross point does not exist.
> 
> 想请问下PGNet训练时能否处理这种label里面点数不同的问题呢？如果可以的话应该怎么操作呢？如果不可以的话应该是不是只能修改成点数相同的标注方法呢，上面的报错又应该怎么解决呢？
> 
> 求指导，谢谢大家~

请问大佬解决这个问题了吗

**Comment by aleaaaa** [comment]
请问大佬，我训练PGNet时，会频繁出现这个问题是什么原因？
root ERROR: When parsing line 906, error happened with msg: Expecting ',' delimiter: line 1 column 626 (char 625)
root ERROR: When parsing line 2984, error happened with msg: setting an array element with a sequence. The requested array has an inhomogeneous
shape after 1 dimensions. The detected shape was (113,) + inhomogeneous part.

**Comment by KingJames1999** [comment]
> 请问大佬，我训练PGNet时，会频繁出现这个问题是什么原因？ root ERROR： 解析行 906 时，使用 msg 发生错误： 期望 '， ' 分隔符： 行 1 列 626 （char 625） 根错误： 解析行 2984 时， 错误与 msg： 设置具有序列的数组元素。请求的数组在 1 个维度后具有不均匀的形状。检测到的形状为（113，）+不均匀部分。

您好像碰到的都是我遇到的问题，能加个联系方式交流一下吗

**Comment by qqqqq127** [comment]
> 请问大佬，我训练PGNet时，会频繁出现这个问题是什么原因？ root ERROR: When parsing line 906, error happened with msg: Expecting ',' delimiter: line 1 column 626 (char 625) root ERROR: When parsing line 2984, error happened with msg: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (113,) + inhomogeneous part.

我也是有这个问题，请问您解决了吗

**Comment by tjpulfn** [comment]
数据的问题，检查一下标注发自我的iPhone------------------ 原始邮件 ------------------发件人: aleaaaa  ***@***.***>发送时间: 2022年3月19日 13:28收件人: PaddlePaddle/PaddleOCR ***@***.***>抄送: tjpulfn ***@***.***>, Comment ***@***.***>主题: Re: [PaddlePaddle/PaddleOCR] 训练PGNet时，多边形框label需要保证点数相同吗 (#3452)
请问大佬，我训练PGNet时，会频繁出现这个问题是什么原因？
root ERROR: When parsing line 906, error happened with msg: Expecting ',' delimiter: line 1 column 626 (char 625)
root ERROR: When parsing line 2984, error happened with msg: setting an array element with a sequence. The requested array has an inhomogeneous
shape after 1 dimensions. The detected shape was (113,) + inhomogeneous part.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/PaddlePaddle/PaddleOCR/issues/3452#issuecomment-1072945393",
"url": "https://github.com/PaddlePaddle/PaddleOCR/issues/3452#issuecomment-1072945393",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
