### ISSUE TITLE
CPU issues

### ISSUE THREAD

**Issue by akansh12** [PaddlePaddle/PaddleOCR#348]
Can I run this on my CPU? If yes, how can I do so? 
Thank you

**Comment by tink2123** [comment]
Yes, you can train and predict on your own GPU. The [Readme](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/README_en.md) provides some instructions for use as a reference. 

The following documents may be helpful to you：

[Quick installation](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/installation_en.md)
[Text detection model training/evaluation/prediction](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/detection_en.md)
[Text recognition model training/evaluation/prediction](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/recognition_en.md)
[Inference](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/inference_en.md)

If you encounter problems during use, please feel free to give feedback.

**Comment by akansh12** [comment]
I am sorry, my mistake, I wanted to ask for CPU.

**Comment by tink2123** [comment]
You can also  run PaddleOCR on CPU. 
1. You need to install the CPU version of paddle first. 
`python3 -m pip install paddlepaddle==1.8.0`

2. Set the use_gpu parameter to False
For predict:
`python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_det_mv3_db/"  --rec_model_dir="./inference/ch_rec_mv3_crnn/" --use_gpu=False`
For training/evaluation/prediction:
`python3 tools/train.py -c configs/{file/name/of/configs} -o Global.use_gpu=False` 

**Note: Using CPU training will be very slow**

**Comment by Sudhanshu-Dubey14** [comment]
@tink2123 thank you for your answer.
We are able to run PaddleOCR on a CPU machine. We are trying to process a lot of images in a loop because we don't know the path of images beforehand but with time the RAM usage increases and eventually it consumes the whole RAM.
I think we need to 'detach' some data after each loop, but we are not sure how.
Can you help us with that?

Also, will it be a problem if we install the GPU version, `paddlepaddle-gpu==1.7.2.post107` to be precise, and then use `use_gpu=False` if we detect that the system does not have a GPU installed? We are doing this because we don't know beforehand if the system will have a GPU or not and we are assuming that the GPU version of PaddleOCR supports CPU.

Thanks.

**Comment by tink2123** [comment]
Sorry for the late reply.
1. At what stage did the problem of memory growth occur, training or prediction？Also, which model are you using?
2. The GPU version of paddle can only be run using the CPU, but if it is determined that `1.7.2.post107` is inconsistent with the environment, it may not be installed correctly. If you are not sure about the environment, you can install the CPU version first, and the model training weights of the two versions can be shared

**Comment by akansh12** [comment]
1. We are actually using DBNET and CRNN model. It grows after few images.

**Comment by tink2123** [comment]
Here are some temporary solutions：
1. Close multi-process:  python3 train.py xxxxx  -o TrainReader.num_workers=1
2. Reduce the number of queues ：
change 
https://github.com/PaddlePaddle/PaddleOCR/blob/9d33e36df550762b204d5fbfd7977a25e31b2c44/ppocr/data/reader_main.py#L75
to
```
return paddle.reader.multiprocess_reader(readers, False, queue_size=320)
```
