### ISSUE TITLE
训练中经常出现killed，目前主要遇到2种情况

### ISSUE THREAD

**Issue by shenchenfei** [PaddlePaddle/PaddleOCR#3546]
情况一：无报错，直接killed，执行的命令与打印信息如图。
![图片](https://user-images.githubusercontent.com/50792800/128282790-7ff18fa0-fca8-41d5-9c2a-536b0d220a2e.png)

情况二：报错如下
![图片](https://user-images.githubusercontent.com/50792800/128282747-cf31a4b8-f544-440e-8585-288f7c22addc.png)

以上两种情况都是间歇性出现，经常跑着跑着就停了，很恶心人，大家是否有遇到？

**Comment by TD-wzw** [comment]
直接被杀大概率是因为内存泄漏的原因，你可以训练的时候监控一下内存是不是一直在涨

**Comment by xiaoyong001** [comment]
楼主，你解决这个问题了吗

**Comment by shenchenfei** [comment]
> 
> 
> 直接被杀大概率是因为内存泄漏的原因，你可以训练的时候监控一下内存是不是一直在涨

我看了一下，直接被杀的确是训着训着内存就超了（总是训了好几个小时，然后突然内存就上去了，不知道为什么），我8卡60G的内存，96*8的batchsize居然都不够用。

**Comment by shenchenfei** [comment]
> 
> 
> 楼主，你解决这个问题了吗

情况一的问题应该就是 @TD-wzw 所说的，我监控了一下内存使用情况，训了一段时间内存就超限了。

**Comment by xiaoyong001** [comment]
好的，非常感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月10日(周二) 上午10:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 训练中经常出现killed，目前主要遇到2种情况 (#3546)




  
直接被杀大概率是因为内存泄漏的原因，你可以训练的时候监控一下内存是不是一直在涨
  
我看了一下，直接被杀的确是训着训着内存就超了（总是训了好几个小时，然后突然内存就上去了，不知道为什么），我8卡60G的内存，96*8的batchsize居然都不够用。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaoyong001** [comment]
好的，非常感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月10日(周二) 上午10:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 训练中经常出现killed，目前主要遇到2种情况 (#3546)




  
楼主，你解决这个问题了吗
  
情况一的问题应该就是 @TD-wzw 所说的，我监控了一下内存使用情况，训了一段时间内存就超限了。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TD-wzw** [comment]
这种问题是训练代码的bug，并不是你们操作的问题，paddle这个框架我不是很了解，有可能是训练每一轮的时候没有清空上一轮的梯度或者某些操作的时候数据类型忘记转换累积的内存

**Comment by xiaoyong001** [comment]
哦哦，好的，非常感谢，您知道怎么解决吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月10日(周二) 上午10:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleOCR] 训练中经常出现killed，目前主要遇到2种情况 (#3546)




 
这种问题是训练代码的bug，并不是你们操作的问题，paddle这个框架我不是很了解，有可能是训练每一轮的时候没有清空上一轮的梯度或者某些操作的时候数据类型忘记转换累积的内存
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TD-wzw** [comment]
paddle不太会，pytorch的话无非就是每轮把梯度清空一下 zero_grad()这样，不清空一直累积梯度会有那种情况
