### ISSUE TITLE
About the table structure recognition algorithm - RARE?

### ISSUE THREAD

**Issue by huyhoang17** [PaddlePaddle/PaddleOCR#3590]
Hi, thanks for the great library!

I want to ask about the `Table structure and cell coordinate prediction` algorithm mentioned in the [README](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.2/ppstructure/table#1-pipeline). Can you provide more information about the RARE model or the related papers? Thank you.

**Comment by MissPenguin** [comment]
RARE is a re-implemented text recognition algorithm in PaddleOCR. You can find the related paper [here](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.2/doc/doc_en/algorithm_overview_en.md#2-text-recognition-algorithm) . RARE can be used for table structure recognition because it can be treated as a similar task as text recognition. The difference is the character sequence is composed of html characters other than general characters.

**Comment by huyhoang17** [comment]
@MissPenguin thanks!
