### ISSUE TITLE
训练模型和推理模型结果不一致

### ISSUE THREAD

**Issue by lalalagogogochong** [PaddlePaddle/PaddleOCR#3822]
使用DBNet训练文本检测模型时，将训练模型转成推理模型之后，检测结果不一样，需要调整哪些参数才能让那个结果一样呢配置文件都是用的ch_det_res18_db_v2.0.yml

**Comment by zhangyingying520** [comment]
> ![image](https://user-images.githubusercontent.com/15188456/130922088-e11a6b8c-200e-41fb-82a4-7819fb7d19ab.png)
> 你试试把这行注释掉看看，我注释掉结果就一样了

麻烦问一下，这个在哪里修改一下

**Comment by zhangyingying520** [comment]
> ![image](https://user-images.githubusercontent.com/15188456/130922088-e11a6b8c-200e-41fb-82a4-7819fb7d19ab.png)
> 你试试把这行注释掉看看，我注释掉结果就一样了

麻烦问一下，这是哪个配置文件

**Comment by lalalagogogochong** [comment]
> > ![image](https://user-images.githubusercontent.com/15188456/130922088-e11a6b8c-200e-41fb-82a4-7819fb7d19ab.png)
> > 你试试把这行注释掉看看，我注释掉结果就一样了
> 
> 麻烦问一下，这是哪个配置文件

这是检测模型转换前后不一致的解决方法，路径是tools/infer/predict_det.py

**Comment by lalalagogogochong** [comment]
> > ![image](https://user-images.githubusercontent.com/15188456/130922088-e11a6b8c-200e-41fb-82a4-7819fb7d19ab.png)
> > 你试试把这行注释掉看看，我注释掉结果就一样了
> 
> 麻烦问一下，这是哪个配置文件

这是检测模型转换前后不一致的解决方法，路径是tools/infer/predict_det.py

> > ![image](https://user-images.githubusercontent.com/15188456/130922088-e11a6b8c-200e-41fb-82a4-7819fb7d19ab.png)
> > 你试试把这行注释掉看看，我注释掉结果就一样了
> 
> 麻烦问一下，这是哪个配置文件

这个是文本检测模型转换后推理结果不一致的解决方法，路径是tools/infer/predict_det.py

**Comment by zhangyingying520** [comment]
好的，谢谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月18日(星期六) 中午11:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleOCR] 训练模型和推理模型结果不一致 (#3822)





   

 你试试把这行注释掉看看，我注释掉结果就一样了
  
麻烦问一下，这是哪个配置文件
  
这是检测模型转换前后不一致的解决方法，路径是tools/infer/predict_det.py
   

 你试试把这行注释掉看看，我注释掉结果就一样了
  
麻烦问一下，这是哪个配置文件
  
这个是文本检测模型转换后推理结果不一致的解决方法，路径是tools/infer/predict_det.py
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangyingying520** [comment]
如果我用官方给的检测模型，用自己训练的识别模型结合着用可以吗

**Comment by lalalagogogochong** [comment]
> 如果我用官方给的检测模型，用自己训练的识别模型结合着用可以吗

可以啊，这个检测和识别是分开的，用官方的检测模型，将检测到的框裁剪出来，可以加个文本方向分类器，然后送到识别网络
