### ISSUE TITLE
Too Much Logging Info

### ISSUE THREAD

**Issue by stevenwalton** [PaddlePaddle/PaddleOCR#4020]
So I've commented in #2348 before and this does not work for me and I've been extremely frustrated with the massive amount of information that goes across my screen. So, I got into the code and to try and find out why this is happening. There's something overwriting logging levels.  The logger is defined at paddleocr.py#L29 which automatically sets the logging level to DEBUG via the construction (ppocr/utils/logging.py#L25).  It is unclear why this can't be changed and created as a global. Problem 1. 

So Setting paddleocr.py#29 to `logger = get_logger(log_level=logging.ERROR)` hasn't helped really. By the time you hit the class construction for PaddleOCR we already have an effective level back at `10` (DEBUG). If you get into the `ocr` function then by that time the logging level is `20` (which is why paddleocr.py#L322 goes off). So I looked at the logger function. Turns out it is being called multiple times so it gets overwritten with the same debug level. That happens at paddleocr.py#L268 because there's the statement 
```
if not params.show_log:
            logger.setLevel(logging.INFO)
```
So if we set `show_log=True` we don't actually reset the logger! So the logic here is backwards. Easy fix. Take out the `not`. Problem 2.

But that's not everything. Checking back at the ocr stage we end up back at `30`!!!! So I'm not entirely sure what's going on here, but I can tell that the authors are playing fast and loose with the logging code. The logger gets overwritten and does not respect the parameters you give it. 

So I cannot find a sane way to set the logging level (preferably to nothing).

**Comment by fernandorovai** [comment]
I need to turn the logs off as well. Any hint on how to disable that, please?

**Comment by marianstefi20** [comment]
@stevenwalton I had the same problem as well, way too much logging (I'm not using the GPU version so I don't know anything about that one). Wasted 2-3 hours of my life looking in the library for the source of so many messages. 

**Things that didn't work:** ❗️
- tried modifying the `show_log` part, changing the log level from INFO to CRITICAL...didn't work. 
- tried piping the stdout to /dev/null...didn't work

What worked 🎊 
For example, let's take the `PaddleOCR` class. It's a subclass of `predict_system.TextSystem` which can be found in `paddleocr/tools/infer/predict_system.py`. If you're doing ocr, the `TextSystem` will actually use the `TextRecognizer` class, found in `paddleocr/tools/infer/predict_rec.py`. There, it has a magic `__call__` method, that will, at some point run `self.predictor.run`.  That `predictor` is initialized in the constructor, like this:
```python
self.predictor, self.input_tensor, self.output_tensors, self.config = utility.create_predictor(args, 'rec', logger)
```
That `utility` module is actually `paddleocr/tools/infer/utility.py`. There you will find the `create_predictor` function, which has, very importantly the following two lines:
```python
config.enable_memory_optim()
# config.disable_glog_info()
```
To suppress all the annoying info from stdout, **UNCOMMENT** that `config.disable_glog_info`. You can party afterward!

What I believe it's happening is that, because PaddleOCR (the repo, not the class), uses `inference` from `paddle` under the hood, and paddle wraps in Python some C++ libraries and other magic things, simply playing with the `logging` module won't solve the issue. That's because the logging is not done by the `logging` module, but most likely by something else.

**Comment by jimmyEtiqa** [comment]
Simply resolve by this:

import logging
os.environ['FLAGS_log_level'] = '3'  #
logging.getLogger("ppocr").setLevel(logging.ERROR)
