### ISSUE TITLE
bad result in Persian text

### ISSUE THREAD

**Issue by mohammad69h94** [PaddlePaddle/PaddleOCR#4048]
Hello, I am testing one text from the Persian language and the results are not good.  and only show 'ج' character and not show digits.
please guide me. thank you.
image and result are attachments
![pelak](https://user-images.githubusercontent.com/38998372/133208791-fa32ba91-2e04-4206-b9e5-fd278276fa99.PNG)
![Capture](https://user-images.githubusercontent.com/38998372/133216327-fb1657cd-8456-44d4-b53d-205e186f0a68.PNG)

.

**Comment by tink2123** [comment]
Sorry, your picture does not work well on our model. Because of the lack of real data in the training samples, we do not understand Persian very well, so the performance is not good enough. 
In addition, are our test samples common in Persian?

![](https://raw.githubusercontent.com/PaddlePaddle/PaddleOCR/release/2.3/doc/imgs_words/persian/fa_1.jpg)

**Comment by mehrdadazizi72** [comment]
> 

no, it's not 
you should use samples like this:
![fa_1157](https://user-images.githubusercontent.com/38887451/189535441-c809ac2c-7a2e-4964-ac2f-3b996123b6b9.png)
![fa_1435](https://user-images.githubusercontent.com/38887451/189535444-14347fb5-c337-4552-abba-fddc785d4d41.png)
