### ISSUE TITLE
FatalError: `Segmentation fault` is detected by the operating system.

### ISSUE THREAD

**Issue by fan1071221** [PaddlePaddle/PaddleOCR#4057]
![未命名](https://user-images.githubusercontent.com/67198246/133283320-4089d210-7433-4a10-a947-80e06ab679ca.png)

**Comment by Zhang-O** [comment]
W0915 13:22:32.239436 61999 analysis_predictor.cc:715] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I0915 13:22:32.350232 61999 graph_pattern_detector.cc:91] ---  detected 14 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_to_mul_pass]
I0915 13:22:32.360725 61999 graph_pattern_detector.cc:91] ---  detected 2 subgraphs
--- Running IR pass [fc_fuse_pass]
I0915 13:22:32.361898 61999 graph_pattern_detector.cc:91] ---  detected 2 subgraphs
--- Running IR pass [fc_elementwise_layernorm_fuse_pass]
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
I0915 13:22:32.364568 61999 graph_pattern_detector.cc:91] ---  detected 2 subgraphs
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
I0915 13:22:32.368468 61999 graph_pattern_detector.cc:91] ---  detected 16 subgraphs
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0915 13:22:32.376652 61999 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0915 13:22:32.397804 61999 memory_optimize_pass.cc:199] Cluster name : lstm_0._generated_var_0  size: 1
I0915 13:22:32.397837 61999 memory_optimize_pass.cc:199] Cluster name : x  size: 384
I0915 13:22:32.397846 61999 memory_optimize_pass.cc:199] Cluster name : lstm_0.tmp_0  size: 512
I0915 13:22:32.397855 61999 memory_optimize_pass.cc:199] Cluster name : lstm_0.tmp_3  size: 1
I0915 13:22:32.397861 61999 memory_optimize_pass.cc:199] Cluster name : softmax_0.tmp_0  size: 27136
I0915 13:22:32.397869 61999 memory_optimize_pass.cc:199] Cluster name : linear_3.tmp_1  size: 27136
I0915 13:22:32.397876 61999 memory_optimize_pass.cc:199] Cluster name : batch_norm_25.tmp_1  size: 2048
I0915 13:22:32.397887 61999 memory_optimize_pass.cc:199] Cluster name : batch_norm_17.tmp_3  size: 4096
I0915 13:22:32.397895 61999 memory_optimize_pass.cc:199] Cluster name : lstm_0.tmp_1  size: 1024
--- Running analysis [ir_graph_to_program_pass]
I0915 13:22:32.445668 61999 analysis_predictor.cc:636] ======= optimize end =======
I0915 13:22:32.447796 61999 naive_executor.cc:98] ---  skip [feed], feed -> x
I0915 13:22:32.449579 61999 naive_executor.cc:98] ---  skip [linear_3.tmp_1], fetch -> fetch
W0915 13:22:32.454612 61999 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.2
W0915 13:22:32.458119 61999 device_context.cc:422] device: 0, cuDNN Version: 8.0.


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1631712158 (unix time) try "date -d @1631712158" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 61999 (TID 0x7f2cf4c20740) from PID 0 ***]

**Comment by windspirit95** [comment]
Hi,
I reduced the batch_size and batch_size_per_card in the yaml file from 14 to 4, and the training code run without error :)
Hope it help you, too.
