### ISSUE TITLE
linux下使用pdserving部署报错。

### ISSUE THREAD

**Issue by coder-sun** [PaddlePaddle/PaddleOCR#441]
Traceback (most recent call last):
  File "ocr_web_server.py", line 24, in <module>
    from paddle_serving_app.reader import DBPostProcess, FilterBoxes, GetRotateCropImage, SortedBoxes
ImportError: cannot import name 'GetRotateCropImage' from 'paddle_serving_app.reader' (/home/sun/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle_serving_app/reader/__init__.py)
![image](https://user-images.githubusercontent.com/25734125/88653959-546eb200-d0ff-11ea-8d89-4b23a17902af.png)
已经安装
paddle-serving-client
paddle-serving-server 
paddle-serving-app

使用的是cpu，另外paddle-serving部署有没有详细的教程，谢谢~

**Comment by sevenold** [comment]
你这个是版本的问题，
参考这个：https://github.com/PaddlePaddle/Serving/issues/748
可以用这个版本试试：https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving
paddle-serving的教程，你可以去这看看：https://github.com/PaddlePaddle/Serving

**Comment by coder-sun** [comment]
> 你这个是版本的问题，
> 参考这个：[PaddlePaddle/Serving#748](https://github.com/PaddlePaddle/Serving/issues/748)
> 可以用这个版本试试：https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving
> paddle-serving的教程，你可以去这看看：https://github.com/PaddlePaddle/Serving

下载了上面链接的那个版本的paddle-serving-app，但是ocr_web_server.py里似乎用的都是gpu版本的，请问有没有cpu版本的呢？

**Comment by sevenold** [comment]
我发的链接里有的，https://paddle-serving.bj.bcebos.com/others/paddle_serving_server_gpu-0.3.2-py2-none-any.whl sevenold 邮箱：sevenold@aliyun.com 签名由 网易邮箱大师 定制 在2020年07月28日 18:46，coder-sun 写道： 你这个是版本的问题， 参考这个：PaddlePaddle/Serving#748 可以用这个版本试试：https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving paddle-serving的教程，你可以去这看看：https://github.com/PaddlePaddle/Serving 下载了上面链接的那个版本的paddle-serving-app，但是ocr_web_server.py里似乎用的都是gpu版本的，请问有没有cpu版本的呢？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by coder-sun** [comment]
> 我发的链接里有的，https://paddle-serving.bj.bcebos.com/others/paddle_serving_server_gpu-0.3.2-py2-none-any.whl sevenold 邮箱：sevenold@aliyun.com 签名由 网易邮箱大师 定制 在2020年07月28日 18:46，coder-sun 写道： 你这个是版本的问题， 参考这个：PaddlePaddle/Serving#748 可以用这个版本试试：https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving paddle-serving的教程，你可以去这看看：https://github.com/PaddlePaddle/Serving 下载了上面链接的那个版本的paddle-serving-app，但是ocr_web_server.py里似乎用的都是gpu版本的，请问有没有cpu版本的呢？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢您的回复，我的机器上没有gpu，所以只能用cpu版本的serving，但是我看代码库里pdserving文件夹里的ocr_web_server.py代码用的就是gpu版本的，没有cpu版本的

**Comment by MissPenguin** [comment]
cpu版本也已经发布，详情参考：https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving
