### ISSUE TITLE
文本检测训练过程中，使用验证集进行评估时，长时间卡着的问题？

### ISSUE THREAD

**Issue by LoveSimons** [PaddlePaddle/PaddleOCR#4582]
使用det_r50_vd_east.yml和det_r50_vd_sast.yml配置文件进行文本检测，采用验证集进行评估，评估时间过长，长时间没有反应，也没有报错？采用其他配置文件没有出现这种问题，请问怎么修改，缩减评估时间？

**Comment by tink2123** [comment]
可以把   eval_batch_step: [0,2000] 修改为：eval_batch_step: [3000, 2000]
从第3000次迭代开始评估，避免前期因为模型训练不到位产生过多冗余的框。

**Comment by guanrenxue** [comment]
非常感谢您的回复，我再尝试一下，重新训练。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月9日(星期二) 下午2:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 文本检测训练过程中，使用验证集进行评估时，长时间卡着的问题？ (Issue #4582)





 
可以把   eval_batch_step: [0,2000] 修改为：eval_batch_step: [3000, 2000]
 从第3000次迭代开始评估，避免前期因为模型训练不到位产生过多冗余的框。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
