### ISSUE TITLE
pdserving部署问题：TypeError: Couldn't build proto file into descriptor pool!

### ISSUE THREAD

**Issue by coder-sun** [PaddlePaddle/PaddleOCR#487]
![image](https://user-images.githubusercontent.com/25734125/89387828-a635be80-d735-11ea-86c9-6da713125164.png)

TypeError: Couldn't build proto file into descriptor pool!

环境是：
paddle-serving-server-gpu==0.3.2
paddle-serving-client==0.3.1
paddle-serving-app==0.1.2
虚拟机中的ubuntu18.04，没有gpu，只有cpu

**Comment by ZhaoyangLi-nju** [comment]
同遇到这个问题， 老哥你解决了吗

**Comment by coder-sun** [comment]
> 同遇到这个问题， 老哥你解决了吗

你什么软硬件环境啊，我还没有解决，我怀疑是环境问题

**Comment by ZhaoyangLi-nju** [comment]
> > 同遇到这个问题， 老哥你解决了吗
> 
> 你什么软硬件环境啊，我还没有解决，我怀疑是环境问题

我也是计划在CPU上跑一下，但是现在在你执行的上一步就错了，老哥你执行上一步是什么指令，我是python -m paddle_serving_server.serve --model ocr_det_model --port 9293
但是跑不起来。就会报这个错

**Comment by coder-sun** [comment]
> > > 同遇到这个问题， 老哥你解决了吗
> > 
> > 
> > 你什么软硬件环境啊，我还没有解决，我怀疑是环境问题
> 
> 我也是计划在CPU上跑一下，但是现在在你执行的上一步就错了，老哥你执行上一步是什么指令，我是python -m paddle_serving_server.serve --model ocr_det_model --port 9293
> 但是跑不起来。就会报这个错

这是rpc的方式启动检测模型，后面那个是启动识别模型。我用这种方式启动检测模型正常，但是用web的方式启动检测模型也会报同样的错误。我在想是不是web的方式出了问题

**Comment by coder-sun** [comment]
> 同遇到这个问题， 老哥你解决了吗

老哥，如果你解决了，记得回复下我，谢谢

**Comment by wangjiawei04** [comment]
https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving 目前先用这里README提供的whl包
出现这个问题的原因是因为paddle serving server和client的protobuf版本不一致。这个在0.3.2上面做了升级。

**Comment by coder-sun** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving 目前先用这里README提供的whl包
> 出现这个问题的原因是因为paddle serving server和client的protobuf版本不一致。这个在0.3.2上面做了升级。

老哥，你放的链接里包都是gpu的啊，cpu使用会报cuda not fount错误

**Comment by wangjiawei04** [comment]
好的 不好意思 我编译一下CPU版本发给你

**Comment by coder-sun** [comment]
> 好的 不好意思 我编译一下CPU版本发给你
您好，不知道您编译好了吗，可以发我下吗？
sunxiangxun777@163.con

**Comment by wangjiawei04** [comment]
> > 好的 不好意思 我编译一下CPU版本发给你
> > 您好，不知道您编译好了吗，可以发我下吗？
> > [sunxiangxun777@163.con](mailto:sunxiangxun777@163.con)

https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving 你看看这里新增了CPU的whl包下载和使用方法。
记得再pull一下代码

**Comment by coder-sun** [comment]
> > > 好的 不好意思 我编译一下CPU版本发给你
> > > 您好，不知道您编译好了吗，可以发我下吗？
> > > [sunxiangxun777@163.con](mailto:sunxiangxun777@163.con)
> 
> https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving 你看看这里新增了CPU的whl包下载和使用方法。
> 记得再pull一下代码
感谢，为什么要pull代码呢，代码也有改变嘛

**Comment by MissPenguin** [comment]
> > > > 好的 不好意思 我编译一下CPU版本发给你
> > > > 您好，不知道您编译好了吗，可以发我下吗？
> > > > [sunxiangxun777@163.con](mailto:sunxiangxun777@163.con)
> > 
> > 
> > https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving 你看看这里新增了CPU的whl包下载和使用方法。
> > 记得再pull一下代码
> > 感谢，为什么要pull代码呢，代码也有改变嘛

对的，代码也有改动

**Comment by coder-sun** [comment]
> > > > > 好的 不好意思 我编译一下CPU版本发给你
> > > > > 您好，不知道您编译好了吗，可以发我下吗？
> > > > > [sunxiangxun777@163.con](mailto:sunxiangxun777@163.con)
> > > 
> > > 
> > > https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving 你看看这里新增了CPU的whl包下载和使用方法。
> > > 记得再pull一下代码
> > > 感谢，为什么要pull代码呢，代码也有改变嘛
> 
> 对的，代码也有改动

使用新的教程仍然会报错，
![image](https://user-images.githubusercontent.com/25734125/90131399-a883c280-dd9e-11ea-97d5-203ac47e817b.png)

ImportError: libcrypto.so.10: cannot open shared object file: No such file or directory

**Comment by wangjiawei04** [comment]
> > > > > > 好的 不好意思 我编译一下CPU版本发给你
> > > > > > 您好，不知道您编译好了吗，可以发我下吗？
> > > > > > [sunxiangxun777@163.con](mailto:sunxiangxun777@163.con)
> > > > 
> > > > 
> > > > https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving 你看看这里新增了CPU的whl包下载和使用方法。
> > > > 记得再pull一下代码
> > > > 感谢，为什么要pull代码呢，代码也有改变嘛
> > 
> > 
> > 对的，代码也有改动
> 
> 使用新的教程仍然会报错，
> ![image](https://user-images.githubusercontent.com/25734125/90131399-a883c280-dd9e-11ea-97d5-203ac47e817b.png)
> 
> ImportError: libcrypto.so.10: cannot open shared object file: No such file or directory

先pip uninstall paddle_serving_client 一下 再按照那个文档的链接重新安装一下。这次打包的whl包里面之前没有带上几个so文件，有用户反馈了这个问题，已经做了修复。

**Comment by steelOneself** [comment]
按照 [pdserving](https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving)中的教程安装paddle_serving_client的时候报
`python -m pip install -U https://paddle-serving.bj.bcebos.com/whl/paddle_serving_client-0.0.0-cp37-none-any.whl https://paddle-serving.bj.bcebos.com/whl/paddle_serving_app-0.0.0-py3-none-any.whl
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Collecting paddle-serving-client==0.0.0
  Using cached https://paddle-serving.bj.bcebos.com/whl/paddle_serving_client-0.0.0-cp37-none-any.whl (46.0 MB)
Collecting paddle-serving-app==0.0.0
  Using cached https://paddle-serving.bj.bcebos.com/whl/paddle_serving_app-0.0.0-py3-none-any.whl (48 kB)
Requirement already satisfied, skipping upgrade: numpy>=1.12 in /home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages (from paddle-serving-client==0.0.0) (1.19.1)
Requirement already satisfied, skipping upgrade: protobuf>=3.11.0 in /home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages (from paddle-serving-client==0.0.0) (3.12.4)
Requirement already satisfied, skipping upgrade: six>=1.10.0 in /home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages (from paddle-serving-client==0.0.0) (1.15.0)
Requirement already satisfied, skipping upgrade: grpcio-tools>=1.28.1 in /home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages (from paddle-serving-client==0.0.0) (1.33.2)
Requirement already satisfied, skipping upgrade: grpcio>=1.28.1 in /home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages (from paddle-serving-client==0.0.0) (1.30.0)
Requirement already satisfied, skipping upgrade: pillow in /home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages (from paddle-serving-app==0.0.0) (7.2.0)
Collecting shapely<=1.6.1
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/97/33/d299b42241bf80fce900c6da3a8f4e40f909e2c936e690f749c2ac2fb05d/Shapely-1.6.1.tar.gz (216 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/zw/anaconda3/envs/ocr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rb4h_x5t/shapely/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rb4h_x5t/shapely/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1inllxap
         cwd: /tmp/pip-install-rb4h_x5t/shapely/
    Complete output (11 lines):
    Failed `CDLL(libgeos_c.so.1)`
    Failed `CDLL(libgeos_c.so)`
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rb4h_x5t/shapely/setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "/tmp/pip-install-rb4h_x5t/shapely/shapely/_buildcfg.py", line 167, in <module>
        fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
      File "/tmp/pip-install-rb4h_x5t/shapely/shapely/_buildcfg.py", line 161, in load_dll
        libname, fallbacks or []))
    OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`
Python的版本是3.7

**Comment by steelOneself** [comment]
上面问题的解决办法

Ubuntu系统执行：
sudo apt-get install libgeos-dev
CentOS系统执行：
sudo yum install geos-devel

**Comment by steelOneself** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/tree/develop/deploy/pdserving 目前先用这里README提供的whl包
> 出现这个问题的原因是因为paddle serving server和client的protobuf版本不一致。这个在0.3.2上面做了升级。

将client的版本和serving的版本，按照操作文档都换成了0.0，版本信息如下：
paddle-serving-app        0.0.0
paddle-serving-client     0.0.0
paddle-serving-server     0.0.0
paddle-serving-server-gpu 0.0.0.post10
paddlepaddle-gpu          2.0.0b0

在不修改params.py的cfg.use_gpu = False参数时候，启动快速版 python ocr_local_server.py  报如下错误：
Traceback (most recent call last):
  File "deploy/pdserving/ocr_local_server.py", line 24, in <module>
    from clas_local_server import TextClassifierHelper
  File "/home/zw/workspace/text_ocr/PaddleOCR/deploy/pdserving/clas_local_server.py", line 30, in <module>
    from paddle_serving_server.web_service import WebService
  File "/home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages/paddle_serving_server/web_service.py", line 24, in <module>
    from paddle_serving_server import pipeline
  File "/home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages/paddle_serving_server/pipeline/__init__.py", line 15, in <module>
    from .operator import Op, RequestOp, ResponseOp
  File "/home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages/paddle_serving_server/pipeline/operator.py", line 41, in <module>
    from . import local_rpc_service_handler
  File "/home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages/paddle_serving_server/pipeline/local_rpc_service_handler.py", line 19, in <module>
    from paddle_serving_server_gpu import OpMaker, OpSeqMaker, Server
  File "/home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages/paddle_serving_server_gpu/__init__.py", line 17, in <module>
    from .proto import server_configure_pb2 as server_sdk
  File "/home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages/paddle_serving_server_gpu/proto/server_configure_pb2.py", line 22, in <module>
    serialized_pb=_b('\n\x16server_configure.proto\x12\x1e\x62\x61idu.paddle_serving.configure\"\xd0\x04\n\nEngineDesc\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x02(\t\x12\x17\n\x0freloadable_meta\x18\x03 \x02(\t\x12\x17\n\x0freloadable_type\x18\x04 \x02(\t\x12\x17\n\x0fmodel_data_path\x18\x05 \x02(\t\x12\x1a\n\x12runtime_thread_num\x18\x06 \x02(\x05\x12\x18\n\x10\x62\x61tch_infer_size\x18\x07 \x02(\x05\x12\x1a\n\x12\x65nable_batch_align\x18\x08 \x02(\x05\x12\x14\n\x0cversion_file\x18\t \x01(\t\x12\x14\n\x0cversion_type\x18\n \x01(\t\x12\x64\n\x19sparse_param_service_type\x18\x0b \x01(\x0e\x32\x41.baidu.paddle_serving.configure.EngineDesc.SparseParamServiceType\x12\'\n\x1fsparse_param_service_table_name\x18\x0c \x01(\t\x12\"\n\x1a\x65nable_memory_optimization\x18\r \x01(\x08\x12\x1b\n\x13static_optimization\x18\x0e \x01(\x08\x12!\n\x19\x66orce_update_static_cache\x18\x0f \x01(\x08\x12\x1e\n\x16\x65nable_ir_optimization\x18\x10 \x01(\x08\x12\x0f\n\x07use_trt\x18\x11 \x01(\x08\"9\n\x16SparseParamServiceType\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05LOCAL\x10\x01\x12\n\n\x06REMOTE\x10\x02\"O\n\x10ModelToolkitConf\x12;\n\x07\x65ngines\x18\x01 \x03(\x0b\x32*.baidu.paddle_serving.configure.EngineDesc\"\x81\x02\n\x0cResourceConf\x12\x1a\n\x12model_toolkit_path\x18\x01 \x02(\t\x12\x1a\n\x12model_toolkit_file\x18\x02 \x02(\t\x12\x1a\n\x12general_model_path\x18\x03 \x01(\t\x12\x1a\n\x12general_model_file\x18\x04 \x01(\t\x12\x18\n\x10\x63ube_config_path\x18\x05 \x01(\t\x12\x18\n\x10\x63ube_config_file\x18\x06 \x01(\t\x12\x17\n\x0f\x63ube_quant_bits\x18\x07 \x01(\x05\x12\x19\n\x11\x61uth_product_name\x18\x08 \x01(\t\x12\x19\n\x11\x61uth_container_id\x18\t \x01(\t\"/\n\x11\x44\x41GNodeDependency\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04mode\x18\x02 \x02(\t\"n\n\x07\x44\x41GNode\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x02(\t\x12G\n\x0c\x64\x65pendencies\x18\x03 \x03(\x0b\x32\x31.baidu.paddle_serving.configure.DAGNodeDependency\"g\n\x08Workflow\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x15\n\rworkflow_type\x18\x02 \x02(\t\x12\x36\n\x05nodes\x18\x03 \x03(\x0b\x32\'.baidu.paddle_serving.configure.DAGNode\"K\n\x0cWorkflowConf\x12;\n\tworkflows\x18\x01 \x03(\x0b\x32(.baidu.paddle_serving.configure.Workflow\"D\n\x13ValueMappedWorkflow\x12\x1b\n\x13request_field_value\x18\x01 \x02(\t\x12\x10\n\x08workflow\x18\x02 \x02(\t\"\xde\x01\n\x0cInferService\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0e\n\x06merger\x18\x02 \x01(\t\x12-\n\x1e\x65nable_map_request_to_workflow\x18\x03 \x01(\x08:\x05\x66\x61lse\x12\x19\n\x11request_field_key\x18\x04 \x01(\t\x12S\n\x16value_mapped_workflows\x18\x05 \x03(\x0b\x32\x33.baidu.paddle_serving.configure.ValueMappedWorkflow\x12\x11\n\tworkflows\x18\x06 \x03(\t\"`\n\x10InferServiceConf\x12\x0c\n\x04port\x18\x01 \x01(\r\x12>\n\x08services\x18\x02 \x03(\x0b\x32,.baidu.paddle_serving.configure.InferService')
  File "/home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 941, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "server_configure.proto":
  server_configure.proto: A file with this name is already in the pool.

使用GPU版本的时候能够正常启动，但是测试的时候报：
[2020-10-30 15:27:25,921] ERROR in app: Exception on /ocr/prediction [POST]
Traceback (most recent call last):
  File "/home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages/paddle_serving_server_gpu/web_service.py", line 230, in run
    return self.get_prediction(request)
  File "/home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages/paddle_serving_server_gpu/web_service.py", line 171, in get_prediction
    request.json["fetch"])
  File "deploy/pdserving/ocr_local_server.py", line 96, in preprocess
    feed, fetch, self.tmp_args = self.text_system.preprocess(im)
  File "deploy/pdserving/ocr_local_server.py", line 57, in preprocess
    fetch_map = self.det_client.predict(feed, fetch)
  File "/home/zw/anaconda3/envs/ocr/lib/python3.7/site-packages/paddle_serving_app/local_predict.py", line 127, in predict
    input_tensor.copy_from_cpu(feed[name])
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   void paddle::ZeroCopyTensor::copy_from_cpu<float>(float const*)
1   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
2   paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
3   paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
4   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
5   paddle::memory::allocation::RetryAllocator::AllocateImpl(unsigned long)
6   paddle::memory::allocation::AutoGrowthBestFitAllocator::AllocateImpl(unsigned long)
7   paddle::memory::allocation::AlignedAllocator::AllocateImpl(unsigned long)
8   paddle::memory::allocation::CUDAAllocator::AllocateImpl(unsigned long)
9   paddle::platform::RecordedCudaMalloc(void**, unsigned long, int)
10  paddle::platform::GetCurrentDeviceId()
11  paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
12  std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
13  paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(3), initialization error.
  [Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:190)
