### ISSUE TITLE
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.   [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/fluid/platform/dynload/cudnn.cc:59)   [operator < gaussian_random > error]

### ISSUE THREAD

**Issue by Rishav-hub** [PaddlePaddle/PaddleOCR#5530]
Image 1-:

![image](https://user-images.githubusercontent.com/57321948/154858060-60262780-90b1-473a-947e-3d9081c12095.png)

Image 2-:
![image](https://user-images.githubusercontent.com/57321948/154858076-1e6f5428-cb45-4ba7-a445-25903d583baa.png)

#####################

Solution Tried(Not Working) -:

![image](https://user-images.githubusercontent.com/57321948/154858120-2ada58a3-a639-4e69-b952-70481687b15a.png)

I am using Data crunch Instance which has(Didn't Work) -:
NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4  

I tried the same thing on colab which had(WORKED) -:
VIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2  

can you help me with this?

**Comment by entbappy** [comment]
having the same issue ,,, Please consider feedback!

**Comment by MissPenguin** [comment]
seems like cudnn problem. Please reinstall PaddlePaddle according to the official tutorial.

**Comment by lokeish** [comment]
[2024/04/19 12:04:42] ppocr WARNING: Since the angle classifier is not initialized, it will not be used during the forward process
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/paddleocr/paddleocr.py", line 668, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
  File "/usr/local/lib/python3.10/dist-packages/paddleocr/tools/infer/predict_system.py", line 76, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/usr/local/lib/python3.10/dist-packages/paddleocr/tools/infer/predict_det.py", line 244, in __call__
    self.input_tensor.copy_from_cpu(img)
  File "/usr/local/lib/python3.10/dist-packages/paddle/inference/wrapper.py", line 52, in tensor_copy_from_cpu
    self._copy_from_cpu_bind(data)
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
  [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/phi/backends/dynload/cudnn.cc:64)

**Comment by lokeish** [comment]
How to solve this issue, my cuda version is 12.2, os is ubuntu, python version is 3.10, paddlepaddle version is 2.6.1

**Comment by Nick-Logika** [comment]
Paddle docs suggest Cuda 11.0-12.0 on Ubunto 18.04 or 20.04.

Paddle works on my 22.04 but not with the cuda 12.2 I have.
