### ISSUE TITLE
Question about the inference benchmark for PaddleOCR v2

### ISSUE THREAD

**Issue by kkkris7** [PaddlePaddle/PaddleOCR#6045]
Hi, this is more like a general question about the inference benchmark. I found for PP-OCRv2, it only costs 111ms with T4 GPU. Could you please provide more details about the configurations? e.g. GPU/CPUmemory size, number of GPU, number of CPU, number of workers, Network bandwith, etc. The reason I am asking is during my testing, the average inference time is about 350ms with one T4 GPU and really need Paddle team's help to troubleshoot it. 

Model Name | CPU | T4 GPU
-- | -- | --
PP-OCRv2 | 330 | 111
PP-OCR mobile | 356 | 116
PP-OCR server | 1056 | 200

Thanks for the great contribution on OCR!

**Comment by LDOUBLEV** [comment]
@kkkris7 Hi
The average prediction time is affected by a variety of factors, including image size, warmup, the average number of text boxes per image, hardware, etc.

Here are my testing results.
![image](https://user-images.githubusercontent.com/26592129/165502107-a5bce114-a90c-4ebd-b415-ad9639a0ebef.png)

- The number of the testing images is 310 and there are 17 detection boxes per image. The time spent on detection and recognition is 13.6s and 21.1s respectively.  (13.6+21.1)*1000/310.≈ 111 ms 
- When testing, the prediction time of the first 1-3 images is very long, because paddleocr initialization takes time.
- I didn't count the average image width and height for 310 images, but it's probably between 640 and 960. Image size is proportional to prediction time
- please set --rec_batch_num=6

![image](https://user-images.githubusercontent.com/26592129/165503264-19d4d6f3-47f6-404d-a6a3-602116213b63.png)

![image](https://user-images.githubusercontent.com/26592129/165503312-7c5ad14c-2097-4fcb-a01d-c69bffc35fb4.png)

**Comment by kkkris7** [comment]
Thank you for sharing this great answer. May I know how to track the time spend on pre-process and post-process for both the detection model and recognition model? Thank you!!

**Comment by MissPenguin** [comment]
> Thank you for sharing this great answer. May I know how to track the time spend on pre-process and post-process for both the detection model and recognition model? Thank you!!

set the parameter "benchmark" as true, the logs will print the pre-process and post-process time cost.
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/tools/infer/predict_system.py#L197
