### ISSUE TITLE
Issue in Recognition of English Alphabets ( ' I ' , ' j ' , ' i ' , ' q ' , ' g ' )

### ISSUE THREAD

**Issue by NaeemKhanNiazi** [PaddlePaddle/PaddleOCR#6538]
Thank you for such a nice work . I am using paddle OCR on the NIC (National Identity card) Document . The NIC document is in English language . The OCR performance is good in most of the time but in some cases it confuse between some of the English alphabets

**Like** 

**Ijaz (Orignal name on NIC Document)  ---->  liaz (OCR predict output) 
Ishaq (Orignal name on NIC Document) ----> Ishag (OCR predict output) 
jiven (Orignal name on NIC Document) -----> ijven Ishag (OCR predict output)** 

How to improve the result for similar looking English alphabets because it is creating problems in reading text properly . Can you suggest me any solution to tackle above problem . 

**-> Suggest me any pre-processing steps which help in improving the results**

Thank You :)

**Comment by MissPenguin** [comment]
Characters with similar appearance may be misidentified. Is it convenient to provide several badcase images for us to test?

**Comment by NaeemKhanNiazi** [comment]
![11](https://user-images.githubusercontent.com/23333363/173563443-b3a5beb7-cc2c-4d62-b6dc-5cf7b1ba4148.jpg)
![22](https://user-images.githubusercontent.com/23333363/173563452-44791daa-0345-4386-98d8-fb85480b20a6.jpg)

**Comment by NaeemKhanNiazi** [comment]
These are some of the Cases where OCR misidentified the characters.

Muhammad Ishaq turn into Muhammad Ishag
Muhammad Ishtiaq turn into Muhammad Ishtiag

**Comment by NaeemKhanNiazi** [comment]
Sadiq Hussain -------------> Turn in to ----------> Sadig Hussain
Muhammad Ijaz Hussain --------> Turn in to ----------> Muhammad liaz Hussain or Muhammad ljaz (start with small L) Hussain

**Comment by tink2123** [comment]
We tested a few pictures and found that most of the recognition errors are because the detection frame is too tight. 

By adjusting the post-processing parameters to expand the detection frame, the related problems can be effectively alleviated. The following commands are for reference：

```
paddleocr --image_dir=nic --lang=en --use_dilation=True --det_db_unclip_ratio=1.8
```
`--det_db_unclip_ratio=1.8` may not be the optimal parameter, you can try multiple adjustments to find the optimal result.

predict result：

<img width="922" alt="image" src="https://user-images.githubusercontent.com/31891223/174003506-cbb4b653-e397-46d0-8d2d-088600e29e6f.png">

<img width="925" alt="image" src="https://user-images.githubusercontent.com/31891223/174003540-4db4c0d4-273b-498b-8b76-cd6629e63408.png">
