### ISSUE TITLE
Question about SVTR implementation and CTCLoss.

### ISSUE THREAD

**Issue by Abdelrahman350** [PaddlePaddle/PaddleOCR#7014]
Hello, I read the paper of the SVTRNet, and your implementation. I have a question about the implementation. While your CTCLoss takes the log_probabilities, you feed the raw probabilities to the CTCLoss without using log_softmax. Is there an explanation for this?

**Comment by Topdu** [comment]
An operator integrating the open source Warp-CTC library (https://github.com/baidu-research/warp-ctc) to compute Connectionist Temporal Classification (CTC) loss. It can be aliased as softmax with CTC, since a native softmax activation is interated to the Warp-CTC library to normalize values for each row of the input tensor.

[PaddlePaddle Doc of CTCLoss](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/CTCLoss_en.html#ctcloss)
