### ISSUE TITLE
Difference between Issues and Discussions

### ISSUE THREAD

**Issue by Evezerest** [PaddlePaddle/PaddleOCR#7240]
Dear Developers,

In more than two years of open source, PaddleOCR has provided industrial-grade OCR systems and end-to-end tools. We are very happy to witness the growth of PaddleOCR with everyone and see a large number of enterprise projects based on PaddleOCR in China. 

**At the same time, as an international open source platform, in order to better serve the needs and solve the problems of international developers, we have opened the [GitHub discussion](https://github.com/PaddlePaddle/PaddleOCR/discussions) and communicated all content in English.**

There are a large number of excellent Chinese notebooks and projects in the PaddleOCR community. We sincerely hope that developers who are good at both English and Chinese can **help us translate these projects into English, or can polish immature English documents so that more international developers learn and join our OCR community.**

We will release an activity plan afterwards to provide more benefits for the community. Looking forward to your participation!

PaddleOCR Team

**Comment by OpenOneV** [comment]
Suppose we need another ML project on inter-language search engine or nlp model that read a paper in one language and talk about it in another. As shown in Wandering Earth.
In the most practical way, translate every other language into English or some middle language may solve the problem.

As for a middle language, DNA use ATCG, which is like ShaoYang01, TaiYang11, ShaoYing10, TaiYing00, in ZhouYi's language. As we have been developed since cells, I suppose we use 乾.Qian； 天 Heaven 坤.Kun；地 Earth 震.Zhen; 雷 Thunder 艮.Gen; 山 Mountain 离.Li; 火 Fire 坎.Kan; 水 Water 兑.Dur; 泽 Lake 巽.Xun; 风 Wind for this middle language. 

Is the search engine middle language the same as ZhouYi or not ?

In ZhouYi's context, many syntaxes are default as "natural", such as when talk about ShaoYang少陽, we say it is of binary code 01, because 
1. ShaoYang少陽 describes Yang inside but Yin outside, 
2. and we divine ZhouYi from bottom up, however, whose result is always spoken or written from top down. It is believed as following the order of nature. 
3. 1 is odd and 0 is even. Yang is odd and Ying is even.
4. The upper the code \ Yao爻 locates, the outer it stands. So, the bottom code \ Yao爻 is (typo:偶發) of the inner energy.

In this way, 01 means outter Yao爻 is Ying, and inner Yao爻 is Yang. It's default as the same as the common nature.

**Comment by Gmgge** [comment]
请问下V4版本近期会正式推出嘛?
