### ISSUE TITLE
paddlelabel标注问题

### ISSUE THREAD

**Issue by juneane** [PaddlePaddle/PaddleOCR#8086]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

**Comment by juneane** [comment]
系统环境/System Environment：Ubuntu20.04
版本号/Version：Paddle： 2.3.2 PaddleOCR：2.6
问题相关组件/Related components：PPOCRLabel
paddleocr环境测试正常，但是安装paddllabel后自动标注闪退且无法输入中文标签。
$ PPOCRLabel --lang ch
[2022/10/25 12:28:17] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
file name in openNext is  /media/wj/newvolume/datasets/yongjiadata/1665989931168.jpg
DirPath in importDirImages is /media/wj/newvolume/datasets/yongjiadata
unicodeFilePath is /media/wj/newvolume/datasets/yongjiadata/1665989931562.jpg
unicodeFilePath is /media/wj/newvolume/datasets/yongjiadata/1665989931552.jpg
unicodeFilePath is /media/wj/newvolume/datasets/yongjiadata/1665989931547.jpg
unicodeFilePath is /media/wj/newvolume/datasets/yongjiadata/1665989931540.jpg
unicodeFilePath is /media/wj/newvolume/datasets/yongjiadata/1665989931536.jpg
unicodeFilePath is /media/wj/newvolume/datasets/yongjiadata/1665989931531.jpg
unicodeFilePath is /media/wj/newvolume/datasets/yongjiadata/1665989931526.jpg
initPos PyQt5.QtCore.QPointF(1522.2727272727273, 641.0)
Cancel creation.
initPos PyQt5.QtCore.QPointF(1518.2727272727273, 645.0)
Using model from  paddle
can only concatenate str (not "list") to str
Traceback (most recent call last):
  File "/home/wj/anaconda3/envs/pp/lib/python3.7/site-packages/PPOCRLabel/libs/autoDialog.py", line 58, in run
    strs += "Transcription: " + chars + " Probability: " + str(cond) + " Location: " + json.dumps(posi) +'\n'
TypeError: can only concatenate str (not "list") to str


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1666672303 (unix time) try "date -d @1666672303" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e80016e8d3) received by PID 1501395 (TID 0x7f1b25452700) from PID 1501395 ***]

Aborted (core dumped)

**Comment by pogevip** [comment]
同样的问题啊，怎么解决

**Comment by heart1999** [comment]
我也是这个问题，这个报错不知道该如何解决。

**Comment by MrKenknight** [comment]
[2022/11/02 16:17:41] ppocr WARNING: When args.layout is false, args.ocr is automatically set to false
file name in openNext is  /home/tungdd7/tungdd7/l/clean_37.jpg
DirPath in importDirImages is /home/tungdd7/tungdd7/l
Using model from  paddle
can only concatenate str (not "list") to str
Traceback (most recent call last):
  File "/home/tungdd7/tungdd7/PaddleOCR/PPOCRLabel/libs/autoDialog.py", line 59, in run
    " Location: " + json.dumps(posi) +'\n'
TypeError: can only concatenate str (not "list") to str


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1667380677 (unix time) try "date -d @1667380677" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e80000dd70) received by PID 56688 (TID 0x7f8dd0600700) from PID 56688 ***]

Aborted (core dumped)



Same problem
