### ISSUE TITLE
Paddle OCR 的训练模型转换为ONNX模型后识别效果发生改变，原来可以正确识别的，转换后识别错误了，请问是什么原因？

### ISSUE THREAD

**Issue by duodance** [PaddlePaddle/PaddleOCR#8149]

**Comment by grinay** [comment]
Same problem. The only thing I figured out recognition works correct with batch sizes 1, If we increase batch sizes, it start predict wrong. The other thing we noticed, if you resize images up to 420 in width it predict correct. However long lines of text will not be recognized.

**Comment by thsno02** [comment]
I also met this issue, and there are two solutions: 
 
+ add a padding operator in the https://github.com/PaddlePaddle/PaddleOCR/blob/d8d76d59c90d922782a4c812f9c720ac77877d5a/tools/infer/predict_rec.py#L332-L341
+ retraining the model with `padding=False`.

Since the `infer_rec.py` calls https://github.com/PaddlePaddle/PaddleOCR/blob/d8d76d59c90d922782a4c812f9c720ac77877d5a/ppocr/data/imaug/rec_img_aug.py#L464-L476 and it contains a padding operator (default setting is `True`), the inference model can yield the consistent results as the training model, while the ONNX model calls `resize_norm_img_svtr`.
