### ISSUE TITLE
use pretrained Text Detection Algorithm

### ISSUE THREAD

**Issue by kbrajwani** [PaddlePaddle/PaddleOCR#900]
If i am running following script 
!python  tools/infer/predict_det.py \
    --image_dir="../Acord27large (2).png" \
    --det_model_dir="../sast_r50_vd_total_text/" \
    --rec_model_dir="ch_ppocr_mobile_v1.1_rec_infer/" \
    --cls_model_dir="ch_ppocr_mobile_v1.1_cls_infer" \
    --rec_batch_num=1 \
    --use_gpu=True \
    --use_angle_cls=True \
    --use_space_char=True     
it works well for detection.

but if i change 
det_algorithm ='SAST'

!python  tools/infer/predict_det.py \
    --image_dir="../Acord27large (2).png" \
    --det_algorithm ='SAST'
    --det_model_dir="../sast_r50_vd_total_text/" \
    --rec_model_dir="ch_ppocr_mobile_v1.1_rec_infer/" \
    --cls_model_dir="ch_ppocr_mobile_v1.1_cls_infer" \
    --rec_batch_num=1 \
    --use_gpu=True \
    --use_angle_cls=True \
    --use_space_char=True     

it's give me  index error at outs_dict['f_score'] = outputs[1] this line.

**Comment by MissPenguin** [comment]
The python script tools/infer/predict_det.py is for detection only, so there is no need for parameters about recognition and text angle classification. Check out the tutorial on detection inference here: https://github.com/PaddlePaddle/PaddleOCR/blob/develop/doc/doc_en/inference_en.md#text-detection-model-inference.

**Comment by kbrajwani** [comment]
@MissPenguin Thanks i am able to run models now. Can you tell me how can we decrease time in SAST model. i am using colab which is giving me k80 gpu.

**Comment by MissPenguin** [comment]
> @MissPenguin Thanks i am able to run models now. Can you tell me how can we decrease time in SAST model. i am using colab which is giving me k80 gpu.

Here are some tips may be helpful:

a. SAST post-processing locality aware NMS has two versions: Python and C++. The speed of C++ version is obviously faster than that of Python version. Due to the compilation version problem of NMS of C++ version, C++ version NMS will be called only in Python 3.5 environment, and python version NMS will be called in other cases.

b. If you don't need to detect curved text, DB is more recommended for speed.

c. Otherwise, you can try to retrain the model with lighter backbones and channel clipping, just as what we did on DB. More details
can be found in the paper: https://arxiv.org/pdf/2009.09941.pdf
