### ISSUE TITLE
max_text_length

### ISSUE THREAD

**Issue by MohieEldinMuhammad** [PaddlePaddle/PaddleOCR#9225]
Can I change the max_text_length parameter and still continue training using a pre-trained model? and how on production paddleocr can infer more than 25 characters but in training the limit is set to 25? Also, what is the drawback of setting the max_text_length to a larger number like 50 for example ?

**Comment by MohieEldinMuhammad** [comment]
@MissPenguin Can you help me understanding this

**Comment by MissPenguin** [comment]
Yes, you can still load a pre-trained model when you change the parameter `max_text_length` .  The value of `max_text_length` is usually considered with [`image_shape`](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml#L90). If you'd like to set `max_text_length` to a larger number, 50 for example, you should set a larger image shape at the same time, like [48, 640, 3]. The CTC-based algorithm supports the recognition of any length of text during inference period. So, 25 is enough for most of the time.

**Comment by mohiiieldin** [comment]
And in inference if the image resize was set as default (48,320) and the number of characters were larger than 25 chars will this decrease the recognition accuracy? Do you have any postprocessing logic to handle this situation (for example splitting the image into 2)

**Comment by MissPenguin** [comment]
> And in inference if the image resize was set as default (48,320) and the number of characters were larger than 25 chars will this decrease the recognition accuracy? Do you have any postprocessing logic to handle this situation (for example splitting the image into 2)

No need to split the image. CTC supports decoding any length of text. That's the main advantage of CTC.

`max_text_length` is set to 25 because the image with more than 25 characters would be blurred too much after resizing to 320, for the convenience of batch training. However, during the inference period, we only need to resize the image to 48 by height, width is not limited. The recognition accuracy won't be affected.

For more information, you can search the relevant materials about CTC algorithm from web.

**Comment by MohieEldinMuhammad** [comment]
thanks a lot this was very helpful @MissPenguin

**Comment by aspaul20** [comment]
@MissPenguin I did both things, changed max_text_length to 140 (that's the longest string in my dataset) and increased image width to 640. But the model gets stuck at 50% accuracy and does not improve any further. Could you guide on how to get 100%?

**Comment by binhere** [comment]
Hi, thank you @MohieEldinMuhammad question and @MissPenguin answer.
This is the first time I have worked on text recognition with PaddleOCR, and I am confused about qualified dataset preparation for obtaining good performance.

Based on the answer, for my understanding, even though training on less than or equal 25 characters max_text_length, when inference, the model still have ability to predict a sentence with longer 25 characters because width is not limited, right?

So my question is:
1. Keeping max_text_length to 25. If my dataset has samples with longer 25 characters, what does the model do with those samples? Do long samples affect the performance?
2. Because width is not limited when inference, does it have any benefit when training with long sentence instead of a few words per sample?
