### ISSUE TITLE
KIE - SDMGR Inferencing

### ISSUE THREAD

**Issue by Siddhijain16** [PaddlePaddle/PaddleOCR#9390]
Hi @WenmuZhou 
Is there any plan to add Python Inference for [SDMGR](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/algorithm_kie_sdmgr_en.md) model for key information extraction?
If possible can you please provide some reference for inferencing?

**Comment by Siddhijain16** [comment]
Hi @tink2123  @Evezerest  Any update on this part ?

**Comment by mineshmathew** [comment]
Can someone help me with the format of the OCR transcriptions that needs to be given for `Global.infer_img` while using  `infer_kie.py` scripts. The inference works when the file has same contents as at the time of training. But for inference since labels are not needed, how must one prepare this file
