### ISSUE TITLE
Batching in text detection - DB at inference time

### ISSUE THREAD

**Issue by prashantkh19** [PaddlePaddle/PaddleOCR#9781]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

Why batching is not supported for text detction?

**Comment by Cute-Yang** [comment]
I think the batching inference is supported  for text deteciton! For DB text detection,the output is just the prob map which has the same shape with the input image! And the preprocessing for input is just to limit the maximum side to 960,so we just set the input  image' shape is 960 x 960 by padding!Now,we have a batch input! And for the post process,we just remove the padding part! you can compare the results of padding and not padding for the input image! I think they must be same! because the db net is just use the conv structure,and in the last part,just use a full conv to make the channel as 1,so the padding part not affect the not padding part！And becasue we make the h and w divided by 32,so the even the boundary of two parts is ok! but if you do like this,will add the compuation because the input is padding! Just try it,if the result is same,share it with me!
